eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:80}}
  client:   
    serviceUrl:
      defaultZone: ${vcap.services.springbox-service-registry.credentials.uri:http://http://springbox-eureka-hemostatic-bacteriologist.cfapps.io/}/eureka/
---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort:80
---
configserver: true
bus: true
